---
title: "Cowplot Transition into Sleep"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'G:/My Drive/Residency/Research/Lab - Damisah/Project - Sleep/Revisions')
```

```{r}
library(tidyverse)
library(viridis)
library(scales)
library(cowplot)
```

## Parameters

Subject01, Feb02 - Transition out of NREM sleep

time = 5820 +/- 340 \| window = +/- 270 \| window_width = 15

```{r}
spectro <- readRDS('Cache/S01_Feb02_spectro_t5820.RDS')
zspike <- readRDS('Cache/S01_Feb02_zspike_t5820.RDS')
swa_1 <- readRDS('Cache/S01_Feb02_swa_t5820_part1.RDS')
spike_1 <- readRDS('Cache/S01_Feb02_spike_raster_t5820_part1.RDS')
swa_2 <- readRDS('Cache/S01_Feb02_swa_t5820_part2.RDS')
spike_2 <- readRDS('Cache/S01_Feb02_spike_raster_t5820_part2.RDS')

output_path_top <- 'Results/S01_Feb02_transition_t5820_top.svg'
output_path_top_px <- 'Results/S01_Feb02_transition_t5820_top.png'
output_path_bot <- 'Results/S01_Feb02_transition_t5820_bottom.svg'
output_path_bot_px <- 'Results/S01_Feb02_transition_t5820_bottom.png'
```

Subject05, Jul12 - Transition out of NREM sleep

time = 13874 +/- 180 \| window = +/- 90 \| window_width = 15

```{r}
# spectro <- readRDS('Cache/S05_Jul12_spectro_t13874.RDS')
# zspike <- readRDS('Cache/S05_Jul12_zspike_t13874.RDS')
# swa_1 <- readRDS('Cache/S05_Jul12_swa_t13874_part1.RDS')
# spike_1 <- readRDS('Cache/S05_Jul12_spike_raster_t13874_part1.RDS')
# swa_2 <- readRDS('Cache/S05_Jul12_swa_t13874_part2.RDS')
# spike_2 <- readRDS('Cache/S05_Jul12_spike_raster_t13874_part2.RDS')
# 
# output_path_top <- 'Results/S05_Jul12_transition_t13874_top.svg'
# output_path_top_px <- 'Results/S0_Jul12_transition_t13874_top.png'
# output_path_bot <- 'Results/S05_Jul12_transition_t13874_bottom.svg'
# output_path_bot_px <- 'Results/S05_Jul12_transition_t13874_bottom.png'
```

## Plotting

```{r}
spectro <- spectro + theme(legend.position = 'none', 
                           plot.margin = unit(c(1, 0, 0, 0), 'cm'))
zspike <- zspike + theme(legend.position = 'none', 
                         plot.margin = unit(c(0, 0, 1, 0), 'cm'))
swa_1 <- swa_1 + theme(legend.position = 'none', 
                       plot.margin = unit(c(1, 0, 0, 0), 'cm'))
spike_1 <- spike_1 + theme(legend.position = 'none', 
                           plot.margin = unit(c(0, 0, 1, 0), 'cm'))
swa_2 <- swa_2 + theme(legend.position = 'none', 
                       plot.margin = unit(c(1, 0, 0, 0), 'cm'))
spike_2 <- spike_2 + theme(legend.position = 'none', 
                           plot.margin = unit(c(0, 0, 1, 0), 'cm'))
```

```{r}
# Top Plot
plot_grid(spectro, zspike, 
          ncol = 1, align = 'v', axis = 'lr',
          rel_heights = c(1, 1))

ggsave(file = output_path_top, width = 10, height = 3.3, 
       dpi = 300, limitsize = FALSE)

ggsave(file = output_path_top_px, 
       width = 2600, height = 780, 
       units = 'px', limitsize = FALSE)
```

```{r}
# Bottom Plot
plot_grid(swa_1, spike_1, swa_2, spike_2, 
          ncol = 1, align = 'v',  axis = 'lr',
          rel_heights = c(1, 1, 1, 1))

ggsave(file = output_path_bot, width = 5, height = 5, 
       dpi = 300, limitsize = FALSE)

ggsave(file = output_path_bot_px, 
       width = 1300, height = 2000, 
       units = 'px', limitsize = FALSE)

```
