---
title: "Event Rasters"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'G:/My Drive/Residency/Research/Lab - Damisah/Project - Sleep')
```

```{r}
library(tidyverse)
```

## Parameters

```{r}
sw_path <- 'Cache/Subject01/S01_SW.csv'
kc_path <- 'Cache/Subject01/S01_KC.csv'
sp_path <- 'Cache/Subject01/S01_SP.csv'
ied_path <- 'Cache/Subject01/S01_IED.csv'
out_path <- 'Results/S01_events_raster.svg'
```

## Munging

```{r}
sw <- read.csv(sw_path)
kc <- read.csv(kc_path)
sp <- read.csv(sp_path)
ied <- read.csv(ied_path)

sw <- sw[, c('Start', 'Channel')]
sw$event <- 'Slow Wave'

kc <- kc[, c('Start', 'Channel')]
kc$event <- 'K-Complex'

sp <- sp[, c('Start', 'Channel')]
sp$event <- 'Spindle'

ied <- rename(ied, Start = start_time)
ied <- ied[, c('Start', 'name')]
colnames(ied) <- c('Start', 'Channel')
ied$event <- 'IED'

data <- rbind(ied, sp, sw, kc)

colnames(data) <- c('time', 'channel', 'event')
data$event <- factor(data$event, levels = c('Slow Wave', 'K-Complex', 'Spindle', 'IED'))
data$time <- round(data$time, digits = 0)/60 # round to nearest second, then give minutes
```

## Plotting

```{r}
ggplot(data, aes(x = time, y = event)) +
  geom_tile(aes(fill = event)) + 
  facet_wrap(channel ~ ., ncol = 5) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = 'Time (min)') +
  theme_minimal() + 
  theme(legend.position = 'none',
        axis.title.x = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 10),
        axis.ticks.x = element_line(size = 0.4),
        axis.ticks.y = element_blank(),
        strip.text = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = 'black', 
                                    fill = NA, 
                                    size = 0.5))
```

```{r}
ggsave(file = out_path, width = 10, height = 14, dpi = 300)
```
