---
title: "Electrode Table"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'Z:/Layton/Sleep_083023')
```

```{r}
library(tidyverse)
library(knitr)
```

## Parameters

```{r}
S01 <- read.csv('Cache/Subject01/Feb02/S01_electrodes.csv')
S05 <- read.csv('Cache/Subject05/S05_electrodes.csv')
```

## Munging

List electrodes by gyrus for Subject01 to aid in manual selection for display

```{r}
# S01 %>%
#   filter(status == 'accept' & 
#          type == 'macro' & 
#          hemisphere == 'right') %>%
#   select(elec_label, roi_1)
```

Count electrodes by YBA-gyrus across the specified patients.

```{r}
S01$subject <- 'Subject01'
S05$subject <- 'Subject05'

d <- rbind(S01, S05); rm(S01, S05)

d <- d[d$status == 'accept' & d$type == 'macro',]
```

```{r}
d <- 
  d %>% 
  group_by(subject, hemisphere, roi_1) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = c(subject, hemisphere), 
              values_from = count,
              values_fill = 0)

write.csv(d, 'Cache/electrode_table.csv', row.names = FALSE)
```
