---
title: "Munging for Scatterplots"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'Z:/Layton/Sleep_083023')
```

```{r}
library(tidyverse)
library(ggh4x)
library(ggExtra)
library(zoo)
library(tune)
library(gghighlight)
```

## Parameters

```{r}
long_hypno_path <- 'Cache/Subject01/Feb02/S01_hypno_epochs_30s.csv'
long_spike_path <- 'Cache/Subject01/Feb02/S01_spike_epochs_30s.csv'
short_hypno_path <- 'Cache/Subject01/Feb02/S01_hypno_epochs_10s.csv'
short_spike_path <- 'Cache/Subject01/Feb02/S01_spike_epochs_10s.csv'
short_sw_path <- 'Cache/Subject01/Feb02/S01_sw_epochs_10s.csv'
sws_corr_path <- 'Cache/Subject01/Feb02/S01_sw_correlation.csv'
legui_path <- 'Cache/Subject01/Feb02/S01_electrodes.csv'
long_out_path <- 'Cache/Subject01/Feb02/long_scatter.csv'
short_out_path <- 'Cache/Subject01/Feb02/short_scatter.csv'
micro_regions <- c('CLA', 'ACC', 'AMY')

# long_hypno_path <- 'Cache/Subject02/Apr26/S02_hypno_epochs_30s.csv' 
# long_spike_path <- 'Cache/Subject02/Apr26/S02_spike_epochs_30s.csv'
# short_hypno_path <- 'Cache/Subject02/Apr26/S02_hypno_epochs_10s.csv' 
# short_spike_path <- 'Cache/Subject02/Apr26/S02_spike_epochs_10s.csv'
# short_sw_path <- 'Cache/Subject02/Apr26/S02_sw_epochs_10s.csv'
# sws_corr_path <- 'Cache/Subject02/Apr26/S02_sw_correlation.csv'
# legui_path <- 'Cache/Subject02/S02_electrodes.csv'
# long_out_path <- 'Cache/Subject02/Apr26/long_scatter.csv'
# short_out_path <- 'Cache/Subject02/Apr26/short_scatter.csv'
# micro_regions <- c('CLA', 'aINS', 'AMY')

# long_hypno_path <- 'Cache/Subject02/Apr27/S02_hypno_epochs_30s.csv'
# long_spike_path <- 'Cache/Subject02/Apr27/S02_spike_epochs_30s.csv'
# short_hypno_path <- 'Cache/Subject02/Apr27/S02_hypno_epochs_10s.csv'
# short_spike_path <- 'Cache/Subject02/Apr27/S02_spike_epochs_10s.csv'
# short_sw_path <- 'Cache/Subject02/Apr27/S02_sw_epochs_10s.csv'
# sws_corr_path <- 'Cache/Subject02/Apr27/S02_sw_correlation.csv'
# legui_path <- 'Cache/Subject02/S02_electrodes.csv'
# long_out_path <- 'Cache/Subject02/Apr27/long_scatter.csv'
# short_out_path <- 'Cache/Subject02/Apr27/short_scatter.csv'
# micro_regions <- c('CLA', 'aINS', 'AMY')
```

## Munging of Long Epochs

```{r}
# Scalp hypnogram
hypno <- 
  read.csv(long_hypno_path) %>%
  mutate(stage = case_when(
    stage == 2 ~ 1,
    stage == 3 ~ 1,
    TRUE ~ 0))

# Spikes
spikes <- 
  read.csv(long_spike_path) %>%
  filter(unit_region %in% micro_regions) %>%
  mutate(unit_region = factor(unit_region, 
                              levels = micro_regions)) %>%
  select(epoch, unit_id, unit_laterality, unit_region, fr)

colnames(spikes) <- c('epoch', 'unit_id', 'unit_laterality', 
                      'unit_region', 'fr')

# Merge data
data <- merge(hypno, spikes, by = 'epoch')

# Calculate z-score of FR
data <- 
  data %>%
  group_by(unit_id) %>%
  mutate(fr_zscore = (fr - mean(fr)) / sd(fr)) %>%
  ungroup()

# Export
write.csv(data, long_out_path, row.names = FALSE)
rm(data)
```

## Munging of Short Epochs

```{r}
# Scalp hypnogram
hypno <- 
  read.csv(short_hypno_path) %>%
  mutate(stage = case_when(
    stage == 2 ~ 1,
    stage == 3 ~ 1,
    TRUE ~ 0))

# Electrode meta-data
legui <- 
  read.csv(legui_path) %>%
  select(elec_label, mni_x, mni_y, mni_z, 
         hemisphere, roi_1)

colnames(legui) <- c('chan_id', 'mni_x', 'mni_y', 'mni_z', 
                     'chan_laterality', 'region')

# # Spike-SWS correlation
# corr <-
#   read.csv(sws_corr_path) %>%
#   select(unit_id, channel, rho, fdr_rho_p_value) %>%
#   filter(fdr_rho_p_value < 0.01)
# 
# colnames(corr) <- c('unit_id', 'chan_id', 'rho', 'p_value')

# Delta Power + Beta Power + Slow Waves
sw <- 
  read.csv(short_sw_path) %>%
  select(epoch, channel, zlog_power, beta_zlog_power, sw_ratio)

colnames(sw) <- c('epoch', 'chan_id', 'delta_zlp', 'beta_zlp', 'sws')

# Spikes
spikes <- 
  read.csv(short_spike_path) %>%
  mutate(unit_region = factor(unit_region, 
                              levels = micro_regions)) %>%
  select(epoch, unit_id, unit_laterality, unit_region, fr)

colnames(spikes) <- c('epoch', 'unit_id', 'unit_laterality', 
                      'unit_region', 'fr')

# Merge data
# data <- merge(corr, sw, by = 'chan_id')
# data <- merge(data, spikes, by = c('unit_id', 'epoch'))
data <- merge(sw, spikes, by = c('epoch'))
data <- merge(data, legui, by = 'chan_id')
data <- merge(data, hypno, by = 'epoch')


# Calculate z-scores
data <- 
  data %>%
  mutate(pair = paste(unit_id, chan_id)) %>%
  group_by(pair) %>%
  mutate(laterality = ifelse(unit_laterality == chan_laterality,
                             'Ipsilateral', 'Contralateral')) %>%
  mutate(laterality = factor(laterality, 
                             levels = c('Ipsilateral', 'Contralateral'))) %>%
  mutate(swa_zscore = delta_zlp,
         beta_zscore = beta_zlp,
         sw_zscore = (sws - mean(sws)) / sd(sws),
         fr_zscore = (fr - mean(fr)) / sd(fr)) %>%
  ungroup()

# Export
write.csv(data, short_out_path, row.names = FALSE)
rm(data)
```
