---
title: "Unit Response"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'Z:/Layton/Sleep_083023')
```

```{r}
library(tidyverse)
library(magrittr)

#install.packages('devtools')
#install_github("jokergoo/ComplexHeatmap")
library(ComplexHeatmap)
library(ComplexUpset)
# library(gapmap)
# library(pheatmap)
# library(gplots)
library(circlize)
```

## Parameters

```{r}
S01_Feb02_input_path <- 'Cache/Subject01/Feb02/S01_unit_response.csv'
S05_Jul11_input_path <- 'Cache/Subject05/Jul11/S05_unit_response.csv'
S05_Jul12_input_path <- 'Cache/Subject05/Jul12/S05_unit_response.csv'
S05_Jul13_input_path <- 'Cache/Subject05/Jul13/S05_unit_response.csv'

barplot_output_path <- 'Results/Combined_response_barplot.svg'
```

## Bar Plot

```{r}
S01_Feb02 <- 
  read.csv(S01_Feb02_input_path) %>%
  mutate(response_type = as.factor(response_type),
         region = as.factor(unit_roi)) %>%
  mutate(response_type = fct_relevel(response_type, 
                                     'Positive', 'None', 'Negative'),
         region = fct_relevel(region, 'R CLA', 'L CLA', 
                                      'R ACC', 'L ACC', 
                                      'R AMY', 'L AMY'))

S05_Jul11 <- 
  read.csv(S05_Jul11_input_path) %>%
  mutate(response_type = as.factor(response_type),
         region = as.factor(unit_roi)) %>%
  mutate(response_type = fct_relevel(response_type, 
                                     'Positive', 'None', 'Negative'),
         region = fct_relevel(region, 'R CLA', 'L CLA', 
                                      'R ACC', 'L ACC', 
                                      'R AMY', 'L AMY'))

S05_Jul12 <- 
  read.csv(S05_Jul12_input_path) %>%
  mutate(response_type = as.factor(response_type),
         region = as.factor(unit_roi)) %>%
  mutate(response_type = fct_relevel(response_type, 
                                     'Positive', 'None', 'Negative'),
         region = fct_relevel(region, 'R CLA', 'L CLA', 
                                      'R ACC', 'L ACC', 
                                      'R AMY', 'L AMY'))

S05_Jul13 <- 
  read.csv(S05_Jul13_input_path) %>%
  mutate(response_type = as.factor(response_type),
         region = as.factor(unit_roi)) %>%
  mutate(response_type = fct_relevel(response_type, 
                                     'Positive', 'None', 'Negative'),
         region = fct_relevel(region, 'R CLA', 'L CLA', 
                                      'R ACC', 'L ACC', 
                                      'R AMY', 'L AMY'))

data <- rbind(S01_Feb02, S05_Jul11, S05_Jul12, S05_Jul13)
```

```{r}
data %>%
  mutate(simple_region = str_extract(region, "CLA|AMY|ACC")) %>%
  group_by(simple_region, response_type) %>%
  summarize(count = n()) %>%
  group_by(simple_region) %>%
  mutate(total = sum(count)) %>%
  mutate(percent = (count / total) * 100) %>%
  select(-count, -total) %>%
  spread(key = response_type, value = percent)
```

```{r}
ggplot(data, aes(x = region, fill = response_type)) + 
    geom_bar() + 
    scale_fill_manual(values = c('#D46A6A', 'gray', '#6A89D4')) +
    theme_minimal() + 
    theme(legend.title = element_blank(),
          legend.text = element_text(size = 16),
          axis.title = element_blank(),
          axis.text.x = element_text(size = 16, angle = 45, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour = 'black', 
                                      fill = NA, 
                                      size = 1))

ggsave(file = barplot_output_path, width = 6, height = 5, 
       dpi = 300, limitsize = FALSE)
```
