---
title: "Channels with most SW's"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'G:/My Drive/Residency/Research/Lab - Damisah/Project - Sleep')
```

```{r}
library(tidyverse)
```

## Parameters

```{r}
sw_path <- 'Cache/Subject01/S01_SW.csv'
legui_path <- 'Cache/Subject01/S01_electrodes.csv'
output_path <- 'Cache/Subject01/S01_best_channels.csv'

# sw_path <- 'Cache/Subject02/Apr26/S02_SW.csv'
# legui_path <- 'Cache/Subject02/S02_electrodes.csv'
# output_path <- 'Cache/Subject02/Apr26/S02_best_channels.csv'

# sw_path <- 'Cache/Subject02/Apr27/S02_SW.csv'
# legui_path <- 'Cache/Subject02/S02_electrodes.csv'
# output_path <- 'Cache/Subject02/Apr27/S02_best_channels.csv'
```

## Munging

```{r}
legui <- read.csv(legui_path)
```

```{r}
d <- 
  read.csv(sw_path) %>%
  group_by(Channel) %>%
  summarize(num_sw = n()) %>%
  merge(x = ., y = legui, 
        by.x = 'Channel', by.y = 'elec_label') %>%
  select(c(Channel, YBA, hemisphere, gyrus, 
           roi_1, roi_2, num_sw)) %>%
  ungroup() %>%
  group_by(roi_2) %>%
  filter(num_sw == max(num_sw))
```

```{r}
write.csv(d, output_path, row.names = FALSE)
```
